# Generated by Django 5.2.14 on 2026-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_room_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='code',
            new_name='invite_code',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='max_players',
            new_name='max_player',
        ),
        migrations.RemoveField(
            model_name='roomplayer',
            name='is_host',
        ),
        migrations.RemoveField(
            model_name='roomplayer',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='roomplayer',
            name='score',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=30),
        ),
    ]
