# Generated by Django 5.2.14 on 2026-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_reapply_room_api_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='draw_time',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='write_time',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddConstraint(
            model_name='roomplayer',
            constraint=models.UniqueConstraint(fields=('room', 'nickname'), name='unique_room_nickname'),
        ),
    ]
