# Generated by Django 5.2.14 on 2026-05-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_draw_time_room_updated_at_room_write_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_turn_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('collecting_prompts', '첫 문장 작성 중'), ('playing', '게임 진행 중'), ('revealing', '결과 공개 중'), ('finished', '종료')], default='collecting_prompts', max_length=30),
        ),
        migrations.CreateModel(
            name='GameChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='game.gamesession')),
                ('starter_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='game.roomplayer')),
            ],
        ),
        migrations.CreateModel(
            name='GameTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('prompt', '첫 문장'), ('drawing', '그림'), ('guess', '그림 설명')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='game.gamechain')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='game.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_turns', to='game.roomplayer')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingReplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_width', models.PositiveIntegerField(default=800)),
                ('canvas_height', models.PositiveIntegerField(default=600)),
                ('events', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replay', to='game.gameturn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gameturn',
            constraint=models.UniqueConstraint(fields=('chain', 'turn_number'), name='unique_chain_turn_number'),
        ),
    ]
